import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { ArrowRight, Globe, Search, Target, Megaphone, Phone, Shield, Zap, Clock } from 'lucide-react';
import { BUSINESS } from '../config/business';
import Hero from '../components/ui/Hero';
import SectionBand from '../components/ui/SectionBand';
import EyebrowHeading from '../components/ui/EyebrowHeading';
import Card from '../components/ui/Card';
import { LinkButton } from '../components/ui/Button';
import ScrollReveal from '../components/ui/ScrollReveal';

// Self-hosted, responsive AVIF/WebP variants generated by scripts/optimize-home-images.mjs.
// Slugs must match IMAGES[].slug in that script.
const services = [
  {
    icon: Globe,
    title: 'Contractor Web Design',
    description: 'Custom websites engineered to convert local traffic into booked jobs. Mobile-first, fast-loading, SEO-ready.',
    href: '/services/contractor-web-design',
    image: 'service-web-design',
  },
  {
    icon: Search,
    title: 'SEO for Contractors',
    description: 'Map Pack-winning local SEO that puts your company in front of homeowners the moment they search.',
    href: '/services/seo-for-contractors',
    image: 'service-seo',
  },
  {
    icon: Target,
    title: 'Google Ads Management',
    description: 'Weather-triggered, geo-targeted PPC campaigns built for contractor demand cycles and seasonal spikes.',
    href: '/services/google-ads-management',
    image: 'service-google-ads',
  },
  {
    icon: Megaphone,
    title: 'Local Service Ads',
    description: 'Google Guaranteed placement that generates verified leads at lower cost than standard search.',
    href: '/services/local-service-ads',
    image: 'service-local-service-ads',
  },
];

const industries = [
  {
    name: 'Roofing',
    href: '/roofing',
    description: 'Storm-ready websites, Map Pack SEO, and weather-triggered ads for roofing contractors.',
    image: 'industry-roofing',
  },
  {
    name: 'HVAC',
    href: '/hvac',
    description: 'Dual-journey sites that capture emergency calls and planned replacements year-round.',
    image: 'industry-hvac',
  },
  {
    name: 'Electrician',
    href: '/electrician',
    description: 'Tuned for panel upgrades, emergency service, and the EV-charger installation boom.',
    image: 'industry-electrician',
  },
];

function HomeImage({ slug, alt, className }: { slug: string; alt: string; className?: string }) {
  const base = `/assets/home/${slug}`;
  return (
    <picture>
      <source
        type="image/avif"
        srcSet={`${base}-480.avif 480w, ${base}-800.avif 800w`}
        sizes="(min-width: 1024px) 50vw, 100vw"
      />
      <source
        type="image/webp"
        srcSet={`${base}-480.webp 480w, ${base}-800.webp 800w`}
        sizes="(min-width: 1024px) 50vw, 100vw"
      />
      <img
        src={`${base}-800.webp`}
        alt={alt}
        width={800}
        height={450}
        className={className}
        loading="lazy"
        decoding="async"
      />
    </picture>
  );
}

const cityLinks = [
  { label: 'Raleigh', href: '/raleigh-web-design' },
  { label: 'Charlotte', href: '/charlotte-web-design' },
  { label: 'Durham', href: '/durham-web-design' },
  { label: 'Greensboro', href: '/greensboro-web-design' },
  { label: 'Winston-Salem', href: '/winston-salem-web-design' },
  { label: 'Fayetteville', href: '/fayetteville-web-design' },
  { label: 'Wilmington', href: '/wilmington-web-design' },
  { label: 'Asheville', href: '/asheville-web-design' },
];

const processSteps = [
  { number: '01', icon: Search, title: 'Free Audit', description: 'We analyze your current site, local competition, and market gaps — no obligation.' },
  { number: '02', icon: Globe, title: 'Design & Build', description: 'Custom site built for conversions with local SEO baked in from day one.' },
  { number: '03', icon: Zap, title: 'Launch & Track', description: 'Zero-downtime launch, tracking configured, Google Search Console submitted.' },
  { number: '04', icon: Clock, title: 'Grow', description: 'Ongoing SEO, ad management, and optimization. Monthly reporting, always.' },
];

const valuePoints = [
  {
    icon: Shield,
    title: 'Contractor-only focus',
    description: 'We don\'t split attention across industries. Every strategy reflects the rhythms of the trades — storm surges, seasonal demand, emergency calls.',
  },
  {
    icon: Globe,
    title: 'Built locally, for locals',
    description: 'Every page we build is engineered to rank in North Carolina markets — from Triangle neighborhoods to coastal zip codes to mountain service areas.',
  },
  {
    icon: Zap,
    title: 'Speed over theater',
    description: 'Sites launch in weeks, not months. No bloated agency process. You talk directly to the people building your site.',
  },
];

export default function HomePage() {
  return (
    <>
      <Helmet>
        <title>Figgle Media — Web Design & SEO for North Carolina Contractors</title>
        <meta name="description" content="Custom websites and local SEO that turn searches into booked jobs for contractors across North Carolina. Get a free website plan." />
        <link rel="canonical" href="https://figglemedia.com/" />
        <meta property="og:title" content="Figgle Media — Web Design & SEO for North Carolina Contractors" />
        <meta property="og:description" content="Custom websites and local SEO that turn searches into booked jobs for contractors across North Carolina." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://figglemedia.com/" />
        <meta property="og:image" content="https://figglemedia.com/assets/logo.webp" />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Organization",
            "name": BUSINESS.name,
            "url": BUSINESS.url,
            "logo": `${BUSINESS.url}/assets/logo.webp`,
            "telephone": BUSINESS.phoneTel,
            "email": BUSINESS.email,
            "address": { "@type": "PostalAddress", "addressLocality": BUSINESS.city, "addressRegion": BUSINESS.state, "addressCountry": "US" },
            "areaServed": { "@type": "State", "name": BUSINESS.serviceArea },
          })}
        </script>
      </Helmet>

      <Hero />

      {/* Why Figgle — value props, no fake numbers */}
      <SectionBand variant="slate" padding="default">
        <ScrollReveal>
          <EyebrowHeading
            eyebrow="Why Figgle"
            title="A marketing agency that actually gets contractors"
            description="Most agencies treat construction like any other industry. We only work with the trades — that's the whole playbook."
            dark
          />
        </ScrollReveal>
        <div className="grid md:grid-cols-3 gap-6 mt-16 max-w-6xl mx-auto">
          {valuePoints.map((v, i) => (
            <ScrollReveal key={v.title} delay={i * 100}>
              <div className="bg-slate-700 rounded-card p-8 shadow-lg border border-white/10 h-full">
                <div className="inline-flex items-center justify-center w-12 h-12 bg-burnt-orange/20 rounded-button mb-5">
                  <v.icon size={24} className="text-burnt-orange" />
                </div>
                <h3 className="text-heading-md text-white mb-3">{v.title}</h3>
                <p className="text-slate-300 leading-relaxed">{v.description}</p>
              </div>
            </ScrollReveal>
          ))}
        </div>
      </SectionBand>

      {/* Services grid */}
      <SectionBand variant="white" padding="default">
        <ScrollReveal>
          <EyebrowHeading
            eyebrow="What We Do"
            title="Everything a contractor needs to dominate online"
            description="Four services, purpose-built for the trades. Choose one, or stack them for compounding results."
            dark
          />
        </ScrollReveal>
        <div className="grid md:grid-cols-2 gap-6 mt-16 max-w-6xl mx-auto">
          {services.map((service, i) => (
            <ScrollReveal key={service.title} delay={i * 100}>
              <Card to={service.href} className="h-full group">
                <div className="aspect-[16/9] overflow-hidden bg-navy-blue/50">
                  <HomeImage
                    slug={service.image}
                    alt=""
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                </div>
                <div className="p-8">
                  <div className="inline-flex items-center justify-center w-12 h-12 bg-burnt-orange/20 rounded-button mb-4">
                    <service.icon size={24} className="text-burnt-orange" />
                  </div>
                  <h3 className="text-heading-lg text-white mb-3 group-hover:text-burnt-orange transition-colors">
                    {service.title}
                  </h3>
                  <p className="text-slate-300 mb-6 leading-relaxed">{service.description}</p>
                  <span className="inline-flex items-center gap-2 text-burnt-orange font-semibold">
                    Learn more
                    <ArrowRight size={16} className="group-hover:translate-x-1 transition-transform" />
                  </span>
                </div>
              </Card>
            </ScrollReveal>
          ))}
        </div>
      </SectionBand>

      {/* Industries */}
      <SectionBand variant="slate" padding="default">
        <ScrollReveal>
          <EyebrowHeading
            eyebrow="Industries We Serve"
            title="Specialist playbooks for the trades"
            description="We don't work with florists, dentists, or SaaS. Just contractors. Every strategy reflects that focus."
            dark
          />
        </ScrollReveal>
        <div className="grid md:grid-cols-3 gap-6 mt-16 max-w-6xl mx-auto">
          {industries.map((ind, i) => (
            <ScrollReveal key={ind.name} delay={i * 100}>
              <Card to={ind.href} className="h-full group overflow-hidden">
                <div className="relative aspect-[4/3] overflow-hidden">
                  <HomeImage
                    slug={ind.image}
                    alt=""
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-navy-blue via-navy-blue/50 to-transparent"></div>
                  <div className="absolute bottom-0 left-0 right-0 p-6">
                    <h3 className="text-heading-lg text-white mb-2">{ind.name}</h3>
                  </div>
                </div>
                <div className="p-6">
                  <p className="text-slate-300 mb-4 leading-relaxed">{ind.description}</p>
                  <span className="inline-flex items-center gap-2 text-burnt-orange font-semibold group-hover:gap-3 transition-all">
                    See {ind.name} marketing
                    <ArrowRight size={16} />
                  </span>
                </div>
              </Card>
            </ScrollReveal>
          ))}
        </div>
      </SectionBand>

      {/* Process */}
      <SectionBand variant="navy" padding="default">
        <ScrollReveal>
          <EyebrowHeading
            eyebrow="Our Process"
            title="A proven 4-step system"
            description="From the first audit to monthly growth — transparent, fast, and tuned to contractor rhythms."
            dark
          />
        </ScrollReveal>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mt-16 max-w-6xl mx-auto">
          {processSteps.map((step, i) => (
            <ScrollReveal key={step.number} delay={i * 100}>
              <div className="relative bg-white/5 backdrop-blur-sm border border-white/10 rounded-card p-6">
                <div className="text-burnt-orange font-display font-extrabold text-5xl opacity-40 mb-2">{step.number}</div>
                <div className="inline-flex items-center justify-center w-10 h-10 bg-burnt-orange/20 rounded-button mb-4">
                  <step.icon size={20} className="text-burnt-orange" />
                </div>
                <h3 className="text-heading-md text-white mb-2">{step.title}</h3>
                <p className="text-slate-300 text-body-sm leading-relaxed">{step.description}</p>
              </div>
            </ScrollReveal>
          ))}
        </div>
        <div className="text-center mt-12">
          <LinkButton to="/our-process" variant="primary" size="md" iconRight={<ArrowRight size={18} />}>
            See the Full Process
          </LinkButton>
        </div>
      </SectionBand>

      {/* Locations */}
      <SectionBand id="cities" variant="white" padding="default">
        <ScrollReveal>
          <EyebrowHeading
            eyebrow="Where We Work"
            title="Serving contractors across North Carolina"
            description="From the Triangle to the coast to the mountains — local strategies for every NC market."
            dark
          />
        </ScrollReveal>
        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-4 mt-16 max-w-5xl mx-auto">
          {cityLinks.map((city) => (
            <Link
              key={city.href}
              to={city.href}
              className="group flex items-center justify-between bg-slate-700 border border-white/10 rounded-button px-5 py-4 hover:border-burnt-orange hover:shadow-lg transition-all"
            >
              <span className="font-semibold text-white group-hover:text-burnt-orange transition-colors">
                {city.label}
              </span>
              <ArrowRight size={16} className="text-slate-400 group-hover:text-burnt-orange group-hover:translate-x-1 transition-all" />
            </Link>
          ))}
        </div>
      </SectionBand>

      {/* Final CTA */}
      <SectionBand variant="dark-navy" padding="feature">
        <div>
          <ScrollReveal>
            <div className="max-w-3xl mx-auto text-center">
              <div className="text-eyebrow uppercase text-burnt-orange mb-4">Get Started</div>
              <h2 className="font-display font-extrabold text-4xl sm:text-5xl md:text-6xl text-white mb-6 tracking-tight">
                Ready to book more jobs?
              </h2>
              <p className="text-body-lg text-slate-200 mb-10 leading-relaxed">
                Get a free custom website plan within 48 hours. No obligation, no contract, no fluff — just a clear picture of what would move the needle for your contracting business.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <LinkButton to="/free-website-plan" variant="primary" size="lg" iconRight={<ArrowRight size={20} />}>
                  Get Your Free Plan
                </LinkButton>
                <a href={`tel:${BUSINESS.phoneTel}`} className="inline-flex items-center justify-center gap-2 px-8 py-4 text-lg text-white font-semibold border-2 border-white/30 rounded-button hover:bg-white/10 transition-all">
                  <Phone size={20} />
                  {BUSINESS.phoneDisplay}
                </a>
              </div>
              <div className="flex flex-wrap justify-center gap-6 mt-10 text-slate-300 text-sm">
                <div className="flex items-center gap-2">
                  <Shield size={16} className="text-burnt-orange" />
                  90-Day Performance Guarantee
                </div>
                <div className="flex items-center gap-2">
                  <Clock size={16} className="text-burnt-orange" />
                  No Long-Term Contracts
                </div>
              </div>
            </div>
          </ScrollReveal>
        </div>
      </SectionBand>
    </>
  );
}
